### ISSUE TITLE
ktx-async crashes with NoSuchMethodError when using 0.16 coroutines version

### ISSUE THREAD

**Issue by amitkot** [libktx/ktx#82]
I'm ktx-async in version 1.9.6-b4 in a game and it crashes with the following exception:

```
06-13 17:27:14.568 18085-18307/com.dev.app E/AndroidRuntime: FATAL EXCEPTION: GLThread 1984
                                                                         Process: com.dev.app, PID: 18085
                                                                         Theme: themes:{}
                                                                         java.lang.NoSuchMethodError: No direct method <init>(Lkotlin/coroutines/experimental/Continuation;Z)V in class Lkotlinx/coroutines/experimental/CancellableContinuationImpl; or its super classes (declaration of 'kotlinx.coroutines.experimental.CancellableContinuationImpl' appears in /data/app/com.dev.app-2/split_lib_dependencies_apk.apk:classes32.dex)
                                                                             at ktx.async.KtxAsync.asynchronous(async.kt:241)
                                                                             at ktx.async.KtxAsync.asynchronous$default(async.kt:94)
                                                                             at com.dev.app.component.ComponentA$sampleAudio$$inlined$let$lambda$1.doResume(ComponentA.kt:81)
                                                                             at com.dev.app.component.ComponentA$sampleAudio$$inlined$let$lambda$1.invoke(ComponentA.kt:0)
                                                                             at com.dev.app.component.ComponentA$sampleAudio$$inlined$let$lambda$1.invoke(ComponentA.kt:15)
                                                                             at ktx.async.AsyncKt$ktxAsync$1.doResume(async.kt:211)
                                                                             at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
                                                                             at ktx.async.KtxContinuation.resume(async.kt:159)
                                                                             at kotlinx.coroutines.experimental.CoroutineDispatcherKt.resumeCancellable(CoroutineDispatcher.kt:197)
                                                                             at kotlinx.coroutines.experimental.CancellableKt.startCoroutineCancellable(Cancellable.kt:34)
                                                                             at kotlinx.coroutines.experimental.CoroutineStart.invoke(CoroutineStart.kt:113)
                                                                             at kotlinx.coroutines.experimental.BuildersKt.launch(Builders.kt:61)
                                                                             at kotlinx.coroutines.experimental.BuildersKt.launch$default(Builders.kt:53)
                                                                             at ktx.async.AsyncKt.ktxAsync(async.kt:210)
                                                                             at com.dev.app.component.ComponentA.sampleAudio(ComponentA.kt:80)
                                                                             at com.dev.app.component.ComponentA.access$sampleAudio(ComponentA.kt:15)
                                                                             at com.dev.app.component.ComponentA$start$$inlined$interval$1.run(timer.kt:37)
                                                                             at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:453)
                                                                             at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
                                                                             at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
0
```

Code:
```kotlin
private fun sampleAudio() {
    required?.let {
        it.initialize()

        ktxAsync {
            asynchronous {
                print(1)
            }

            print(2)
        }
    }
}
```

My Game class contains:
```kotlin
    override fun create() {
        enableKtxCoroutines(asynchronousExecutorConcurrencyLevel = 1)
        ...
    }
```

And my build.gradle contains:
```gradle
dependencies {
    ...
    compile "org.jetbrains.kotlinx:kotlinx-coroutines-core:0.16"
    ...
    compile "io.github.libktx:ktx-async:1.9.6-b4"
}
```

**Comment by czyzby** [comment]
Which Kotlin version are you using? I've noticed that `1.1.2-4` is somewhat buggy, have you tried using `1.1.2-3`?

**Comment by amitkot** [comment]
@czyzby I'm actually using ```1.1.2-3```.

**Comment by czyzby** [comment]
It's the coroutines version. `ktx-async` was implemented using `0.15`, not `0.16`. It seems that the API has changed since then. I'll address the issue - please use `kotlinx-coroutines-core:0.15` for now.

**Comment by czyzby** [comment]
It seems that `0.15` and `0.16` are incompatible, after changing the coroutines library version I can no longer reproduce the issue. Try using `1.9.6-SNAPSHOT` version for now, I'll release `1.9.6-b5` with the "fix" soon.

**Comment by czyzby** [comment]
@amitkot `1.9.6-b5` was released. You should be able to use `0.16` without any problems.

**Comment by amitkot** [comment]
👍 
Thanks!
