### ISSUE TITLE
Default functional parameters in inlined builder methods

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#94]
- [x] Scene2D builders.
- [x] Scene2D style builders (`ktx-style`, `ktx-vis-style`).
- [x] Box2D DSL.
- [x] Ashley DSL.

--- 

[Kotlin 1.2](https://blog.jetbrains.com/kotlin/2017/06/early-access-program-for-kotlin-1-2-has-been-started/) brings inline functions with optional functional parameters. Currently `ktx-scene2d` defines two factory methods for each widget: one with and one without the building block, as you could not simply make the building block optional with `init: Actor.() -> Unit = {}` without removing the `inline` keyword. When Kotlin 1.2 comes out, we can refactor the existing actors' factory methods to use default no-op building blocks and remove the no-init-block methods - without breaking the existing KTX applications.

```Kotlin
// Kotlin 1.1:
inline fun KWidget<*>.button(
    style: String = defaultStyle,
    skin: Skin = Scene2DSkin.defaultSkin) = appendActor(KButton(skin, style))

inline fun <S> KWidget<S>.button(
    style: String = defaultStyle,
    skin: Skin = Scene2DSkin.defaultSkin,
    init: KButton.(S) -> Unit) = actor(KButton(skin, style), init)

// Kotlin 1.2:
inline fun <S> KWidget<S>.button(
    style: String = defaultStyle,
    skin: Skin = Scene2DSkin.defaultSkin,
    init: KButton.(S) -> Unit = {}) = actor(KButton(skin, style), init)
```

**Comment by czyzby** [comment]
Note that this might also be useful for Box2D body/fixture builders.

**Comment by czyzby** [comment]
@Jkly `ktx-ashley` could also benefit from this feature, if I'm not mistaken. Can you take a look?

**Comment by czyzby** [comment]
Inlining text tooltip factory methods [seems to cause compiler errors](https://github.com/libktx/ktx/commit/2f54ebafe31a5eb332c8452487b02510f3e19c64#diff-73905c72eb23c7cba79c23c4d1d41425R6).

```java
org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't inline method call 'addTooltip' into
@org.junit.Test public final fun `should add Tooltip with init block`(): kotlin.Unit defined in ktx.scene2d.TooltipFactoriesTest
@Test
  fun `should add Tooltip with init block`() {
    val actor = Actor()
    val tooltip = actor.addTooltip {
      // Changing Table color:
      color = Color.BLUE
      // Adding child to Table content:
      label("Test.")
    }
    assertNotNull(tooltip)
    assertTrue(tooltip in actor.listeners)
    assertEquals("Test.", (tooltip.actor.children.first() as Label).text.toString())
    assertEquals(Color.BLUE, tooltip.actor.color)
  }
Cause: addTooltip$default (Lcom/badlogic/gdx/scenes/scene2d/Actor;Ljava/lang/String;Lcom/badlogic/gdx/scenes/scene2d/ui/Skin;Lcom/badlogic/gdx/scenes/scene2d/ui/TooltipManager;Lkotlin/jvm/functions/Function2;ILjava/lang/Object;)Lcom/badlogic/gdx/scenes/scene2d/ui/Tooltip;:
  @Lorg/jetbrains/annotations/NotNull;() // invisible
   L0
   L1
    LINENUMBER 43 L1
    ACONST_NULL
    CHECKCAST java/lang/String
    ASTORE 1
   L2
   L3
    LINENUMBER 44 L3
    GETSTATIC ktx/scene2d/Scene2DSkin.INSTANCE : Lktx/scene2d/Scene2DSkin;
    INVOKEVIRTUAL ktx/scene2d/Scene2DSkin.getDefaultSkin ()Lcom/badlogic/gdx/scenes/scene2d/ui/Skin;
    ASTORE 2
   L4
   L5
    LINENUMBER 45 L5
    INVOKESTATIC com/badlogic/gdx/scenes/scene2d/ui/TooltipManager.getInstance ()Lcom/badlogic/gdx/scenes/scene2d/ui/TooltipManager;
    DUP
    LDC "TooltipManager.getInstance()"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkExpressionValueIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    ASTORE 3
   L6
   L7
    ALOAD 0
    LDC "$receiver"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    ALOAD 2
    LDC "skin"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    ALOAD 3
    LDC "tooltipManager"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    ALOAD 4
    LDC "init"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
   L8
    LINENUMBER 61 L8
    NEW ktx/scene2d/KTableWidget
    DUP
    ALOAD 2
    INVOKESPECIAL ktx/scene2d/KTableWidget.<init> (Lcom/badlogic/gdx/scenes/scene2d/ui/Skin;)V
    ASTORE 6
   L9
    LINENUMBER 62 L9
    ALOAD 1
    IFNULL L10
   L11
    LINENUMBER 63 L11
    ALOAD 6
    ALOAD 1
    INVOKEVIRTUAL ktx/scene2d/KTableWidget.setBackground (Ljava/lang/String;)V
   L10
    LINENUMBER 65 L10
    NEW com/badlogic/gdx/scenes/scene2d/ui/Tooltip
    DUP
    ALOAD 6
    CHECKCAST com/badlogic/gdx/scenes/scene2d/Actor
    ALOAD 3
    INVOKESPECIAL com/badlogic/gdx/scenes/scene2d/ui/Tooltip.<init> (Lcom/badlogic/gdx/scenes/scene2d/Actor;Lcom/badlogic/gdx/scenes/scene2d/ui/TooltipManager;)V
    ASTORE 7
   L12
    LINENUMBER 66 L12
    ALOAD 4
    ALOAD 6
    ALOAD 7
    INVOKEINTERFACE kotlin/jvm/functions/Function2.invoke (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    POP
   L13
    LINENUMBER 67 L13
    ALOAD 0
    ALOAD 7
    CHECKCAST com/badlogic/gdx/scenes/scene2d/EventListener
    INVOKEVIRTUAL com/badlogic/gdx/scenes/scene2d/Actor.addListener (Lcom/badlogic/gdx/scenes/scene2d/EventListener;)Z
    POP
   L14
    LINENUMBER 68 L14
    ALOAD 7
    ARETURN
   L15
    LOCALVARIABLE tooltip Lcom/badlogic/gdx/scenes/scene2d/ui/Tooltip; L12 L15 7
    LOCALVARIABLE table Lktx/scene2d/KTableWidget; L9 L15 6
    LOCALVARIABLE $receiver Lcom/badlogic/gdx/scenes/scene2d/Actor; L0 L15 0
    LOCALVARIABLE background Ljava/lang/String; L2 L15 1
    LOCALVARIABLE skin Lcom/badlogic/gdx/scenes/scene2d/ui/Skin; L4 L15 2
    LOCALVARIABLE tooltipManager Lcom/badlogic/gdx/scenes/scene2d/ui/TooltipManager; L6 L15 3
    LOCALVARIABLE init Lkotlin/jvm/functions/Function2; L0 L15 4
    LOCALVARIABLE $i$f$addTooltip I L7 L15 5
    MAXSTACK = 4
    MAXLOCALS = 8
Cause: Unmapped line number in inlined function invoke:152
File being compiled and position: (44,25) in /home/mj/Workspace/ktx/scene2d/src/test/kotlin/ktx/scene2d/tooltipTest.kt
PsiElement: addTooltip {
      // Changing Table color:
      color = Color.BLUE
      // Adding child to Table content:
      label("Test.")
    }
The root cause was thrown at: SMAPAndMethodNode.kt:38
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.throwCompilationException(InlineCodegen.kt:132)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.performInline(InlineCodegen.kt:180)
	at org.jetbrains.kotlin.codegen.inline.PsiInlineCodegen.genCallInner(InlineCodegen.kt:648)
	at org.jetbrains.kotlin.codegen.CallGenerator$DefaultImpls.genCall(CallGenerator.kt:106)
	at org.jetbrains.kotlin.codegen.inline.PsiInlineCodegen.genCall(InlineCodegen.kt:634)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2301)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2252)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:44)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:23)
	at org.jetbrains.kotlin.codegen.OperationStackValue.putSelector(StackValue.kt:75)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:105)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:98)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.initializeLocalVariable(ExpressionCodegen.java:3720)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitProperty(ExpressionCodegen.java:3593)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitProperty(ExpressionCodegen.java:120)
	at org.jetbrains.kotlin.psi.KtProperty.accept(KtProperty.java:57)
	at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitKtElement(CodegenStatementVisitor.java:31)
	at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitKtElement(CodegenStatementVisitor.java:22)
	at org.jetbrains.kotlin.psi.KtVisitor.visitExpression(KtVisitor.java:182)
	at org.jetbrains.kotlin.psi.KtVisitor.visitDeclaration(KtVisitor.java:29)
	at org.jetbrains.kotlin.psi.KtVisitor.visitNamedDeclaration(KtVisitor.java:398)
	at org.jetbrains.kotlin.psi.KtVisitor.visitProperty(KtVisitor.java:57)
	at org.jetbrains.kotlin.psi.KtProperty.accept(KtProperty.java:57)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:307)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genStatement(ExpressionCodegen.java:372)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.generateBlock(ExpressionCodegen.java:1191)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.generateBlock(ExpressionCodegen.java:1141)
	at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitBlockExpression(CodegenStatementVisitor.java:56)
	at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitBlockExpression(CodegenStatementVisitor.java:22)
	at org.jetbrains.kotlin.psi.KtBlockExpression.accept(KtBlockExpression.java:44)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:307)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genStatement(ExpressionCodegen.java:372)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.gen(ExpressionCodegen.java:338)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.returnExpression(ExpressionCodegen.java:1588)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$FunctionDefault.doGenerateBody(FunctionGenerationStrategy.java:56)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$CodegenBased.generateBody(FunctionGenerationStrategy.java:76)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:570)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:333)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:299)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:177)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.gen(FunctionCodegen.java:148)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:210)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateDeclaration(ClassBodyCodegen.java:168)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateBody(ClassBodyCodegen.java:84)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:142)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:316)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:300)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassOrObject(PackageCodegenImpl.java:156)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:86)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:119)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:66)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.generatePackage(KotlinCodegenFacade.java:100)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:78)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:45)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:450)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:152)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:158)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:61)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:353)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:86)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:213)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:83)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.execIncrementalCompiler(CompileServiceImpl.kt:515)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$execIncrementalCompiler(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:399)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:892)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:919)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:891)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:398)
	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unmapped line number in inlined function invoke:152
	at org.jetbrains.kotlin.codegen.inline.SMAPAndMethodNodeKt$createLineNumberSequence$1.invoke(SMAPAndMethodNode.kt:38)
	at org.jetbrains.kotlin.codegen.inline.SMAPAndMethodNodeKt$createLineNumberSequence$1.invoke(SMAPAndMethodNode.kt)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:148)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:148)
	at kotlin.sequences.DistinctIterator.computeNext(Sequences.kt:497)
	at kotlin.collections.AbstractIterator.tryToComputeNext(AbstractIterator.kt:37)
	at kotlin.collections.AbstractIterator.hasNext(AbstractIterator.kt:24)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:633)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:663)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:654)
	at org.jetbrains.kotlin.codegen.inline.SMAPAndMethodNode.<init>(SMAPAndMethodNode.kt:26)
	at org.jetbrains.kotlin.codegen.inline.ExpressionLambda.generateLambdaBody(LambdaInfo.kt:285)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.generateClosuresBodies(InlineCodegen.kt:316)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.inlineCall(InlineCodegen.kt:249)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.performInline(InlineCodegen.kt:171)
	... 89 more
```

**Comment by czyzby** [comment]
[The compiler error is to be fixed in `1.2.10`.](https://youtrack.jetbrains.com/issue/KT-20821)

**Comment by Jkly** [comment]
@czyzby I've created a PR to do this for ktx-ashley here https://github.com/libktx/ktx/pull/115

**Comment by czyzby** [comment]
Still getting the error in Kotlin 1.2.10.

**Comment by czyzby** [comment]
Default functional parameters for inlined methods were added everywhere I could think of that seemed to make sense. I'm closing this issue for now, but feel free to reopen or create a separate ticket if any other modules could use some improvements.
